from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession


class PartitionManager:
    """PostgreSQL 分区表管理器"""
    
    def __init__(self, db_session: AsyncSession):
        self.db = db_session
    
    async def create_partition_tables(self, table_name: str, start_year: int, end_year: int):
        version_result = await self.db.execute(text("SELECT version()"))
        version = version_result.scalar()
        
        if "PostgreSQL 11" not in version and "PostgreSQL 12" not in version and "PostgreSQL 13" not in version and "PostgreSQL 14" not in version and "PostgreSQL 15" not in version and "PostgreSQL 16" not in version:
            raise Exception(f"当前 PostgreSQL 版本不支持分区表: {version}")
        
        await self._create_main_table(table_name)
        
        for year in range(start_year, end_year + 1):
            await self._create_partition_table(table_name, year)
        
        return True
    
    async def _create_main_table(self, table_name: str):
        if table_name == "stock_factor_pro":
            sql = """
            CREATE TABLE IF NOT EXISTS stock_factor_pro (
                ts_code VARCHAR(20),
                trade_date VARCHAR(10),
                -- 基础字段
                open FLOAT,
                high FLOAT,
                low FLOAT,
                close FLOAT,
                pre_close FLOAT,
                change FLOAT,
                pct_chg FLOAT,
                vol FLOAT,
                amount FLOAT,
                -- 复权字段
                open_hfq FLOAT,
                open_qfq FLOAT,
                high_hfq FLOAT,
                high_qfq FLOAT,
                low_hfq FLOAT,
                low_qfq FLOAT,
                close_hfq FLOAT,
                close_qfq FLOAT,
                -- 财务指标
                turnover_rate FLOAT,
                turnover_rate_f FLOAT,
                volume_ratio FLOAT,
                pe FLOAT,
                pe_ttm FLOAT,
                pb FLOAT,
                ps FLOAT,
                ps_ttm FLOAT,
                dv_ratio FLOAT,
                dv_ttm FLOAT,
                total_share FLOAT,
                float_share FLOAT,
                free_share FLOAT,
                total_mv FLOAT,
                circ_mv FLOAT,
                adj_factor FLOAT,
                -- 技术指标 - bfq
                asi_bfq FLOAT,
                asit_bfq FLOAT,
                atr_bfq FLOAT,
                bbi_bfq FLOAT,
                bias1_bfq FLOAT,
                bias2_bfq FLOAT,
                bias3_bfq FLOAT,
                boll_lower_bfq FLOAT,
                boll_mid_bfq FLOAT,
                boll_upper_bfq FLOAT,
                brar_ar_bfq FLOAT,
                brar_br_bfq FLOAT,
                cci_bfq FLOAT,
                cr_bfq FLOAT,
                dfma_dif_bfq FLOAT,
                dfma_difma_bfq FLOAT,
                dmi_adx_bfq FLOAT,
                dmi_adxr_bfq FLOAT,
                dmi_mdi_bfq FLOAT,
                dmi_pdi_bfq FLOAT,
                downdays FLOAT,
                updays FLOAT,
                dpo_bfq FLOAT,
                madpo_bfq FLOAT,
                ema_bfq_10 FLOAT,
                ema_bfq_20 FLOAT,
                ema_bfq_250 FLOAT,
                ema_bfq_30 FLOAT,
                ema_bfq_5 FLOAT,
                ema_bfq_60 FLOAT,
                ema_bfq_90 FLOAT,
                emv_bfq FLOAT,
                maemv_bfq FLOAT,
                expma_12_bfq FLOAT,
                expma_50_bfq FLOAT,
                kdj_bfq FLOAT,
                kdj_d_bfq FLOAT,
                kdj_k_bfq FLOAT,
                ktn_down_bfq FLOAT,
                ktn_mid_bfq FLOAT,
                ktn_upper_bfq FLOAT,
                lowdays FLOAT,
                topdays FLOAT,
                ma_bfq_10 FLOAT,
                ma_bfq_20 FLOAT,
                ma_bfq_250 FLOAT,
                ma_bfq_30 FLOAT,
                ma_bfq_5 FLOAT,
                ma_bfq_60 FLOAT,
                ma_bfq_90 FLOAT,
                macd_bfq FLOAT,
                macd_dea_bfq FLOAT,
                macd_dif_bfq FLOAT,
                mass_bfq FLOAT,
                ma_mass_bfq FLOAT,
                mfi_bfq FLOAT,
                mtm_bfq FLOAT,
                mtmma_bfq FLOAT,
                obv_bfq FLOAT,
                psy_bfq FLOAT,
                psyma_bfq FLOAT,
                roc_bfq FLOAT,
                maroc_bfq FLOAT,
                rsi_bfq_12 FLOAT,
                rsi_bfq_24 FLOAT,
                rsi_bfq_6 FLOAT,
                taq_down_bfq FLOAT,
                taq_mid_bfq FLOAT,
                taq_up_bfq FLOAT,
                trix_bfq FLOAT,
                trma_bfq FLOAT,
                vr_bfq FLOAT,
                wr_bfq FLOAT,
                wr1_bfq FLOAT,
                xsii_td1_bfq FLOAT,
                xsii_td2_bfq FLOAT,
                xsii_td3_bfq FLOAT,
                xsii_td4_bfq FLOAT,
                -- hfq
                asi_hfq FLOAT,
                asit_hfq FLOAT,
                atr_hfq FLOAT,
                bbi_hfq FLOAT,
                bias1_hfq FLOAT,
                bias2_hfq FLOAT,
                bias3_hfq FLOAT,
                boll_lower_hfq FLOAT,
                boll_mid_hfq FLOAT,
                boll_upper_hfq FLOAT,
                brar_ar_hfq FLOAT,
                brar_br_hfq FLOAT,
                cci_hfq FLOAT,
                cr_hfq FLOAT,
                dfma_dif_hfq FLOAT,
                dfma_difma_hfq FLOAT,
                dmi_adx_hfq FLOAT,
                dmi_adxr_hfq FLOAT,
                dmi_mdi_hfq FLOAT,
                dmi_pdi_hfq FLOAT,
                dpo_hfq FLOAT,
                madpo_hfq FLOAT,
                ema_hfq_10 FLOAT,
                ema_hfq_20 FLOAT,
                ema_hfq_250 FLOAT,
                ema_hfq_30 FLOAT,
                ema_hfq_5 FLOAT,
                ema_hfq_60 FLOAT,
                ema_hfq_90 FLOAT,
                emv_hfq FLOAT,
                maemv_hfq FLOAT,
                expma_12_hfq FLOAT,
                expma_50_hfq FLOAT,
                kdj_hfq FLOAT,
                kdj_d_hfq FLOAT,
                kdj_k_hfq FLOAT,
                ktn_down_hfq FLOAT,
                ktn_mid_hfq FLOAT,
                ktn_upper_hfq FLOAT,
                lowdays_hfq FLOAT,
                topdays_hfq FLOAT,
                ma_hfq_10 FLOAT,
                ma_hfq_20 FLOAT,
                ma_hfq_250 FLOAT,
                ma_hfq_30 FLOAT,
                ma_hfq_5 FLOAT,
                ma_hfq_60 FLOAT,
                ma_hfq_90 FLOAT,
                macd_hfq FLOAT,
                macd_dea_hfq FLOAT,
                macd_dif_hfq FLOAT,
                mass_hfq FLOAT,
                ma_mass_hfq FLOAT,
                mfi_hfq FLOAT,
                mtm_hfq FLOAT,
                mtmma_hfq FLOAT,
                obv_hfq FLOAT,
                psy_hfq FLOAT,
                psyma_hfq FLOAT,
                roc_hfq FLOAT,
                maroc_hfq FLOAT,
                rsi_hfq_12 FLOAT,
                rsi_hfq_24 FLOAT,
                rsi_hfq_6 FLOAT,
                taq_down_hfq FLOAT,
                taq_mid_hfq FLOAT,
                taq_up_hfq FLOAT,
                trix_hfq FLOAT,
                trma_hfq FLOAT,
                vr_hfq FLOAT,
                wr_hfq FLOAT,
                wr1_hfq FLOAT,
                xsii_td1_hfq FLOAT,
                xsii_td2_hfq FLOAT,
                xsii_td3_hfq FLOAT,
                xsii_td4_hfq FLOAT,
                -- qfq
                asi_qfq FLOAT,
                asit_qfq FLOAT,
                atr_qfq FLOAT,
                bbi_qfq FLOAT,
                bias1_qfq FLOAT,
                bias2_qfq FLOAT,
                bias3_qfq FLOAT,
                boll_lower_qfq FLOAT,
                boll_mid_qfq FLOAT,
                boll_upper_qfq FLOAT,
                brar_ar_qfq FLOAT,
                brar_br_qfq FLOAT,
                cci_qfq FLOAT,
                cr_qfq FLOAT,
                dfma_dif_qfq FLOAT,
                dfma_difma_qfq FLOAT,
                dmi_adx_qfq FLOAT,
                dmi_adxr_qfq FLOAT,
                dmi_mdi_qfq FLOAT,
                dmi_pdi_qfq FLOAT,
                dpo_qfq FLOAT,
                madpo_qfq FLOAT,
                ema_qfq_10 FLOAT,
                ema_qfq_20 FLOAT,
                ema_qfq_250 FLOAT,
                ema_qfq_30 FLOAT,
                ema_qfq_5 FLOAT,
                ema_qfq_60 FLOAT,
                ema_qfq_90 FLOAT,
                emv_qfq FLOAT,
                maemv_qfq FLOAT,
                expma_12_qfq FLOAT,
                expma_50_qfq FLOAT,
                kdj_qfq FLOAT,
                kdj_d_qfq FLOAT,
                kdj_k_qfq FLOAT,
                ktn_down_qfq FLOAT,
                ktn_mid_qfq FLOAT,
                ktn_upper_qfq FLOAT,
                lowdays_qfq FLOAT,
                topdays_qfq FLOAT,
                ma_qfq_10 FLOAT,
                ma_qfq_20 FLOAT,
                ma_qfq_250 FLOAT,
                ma_qfq_30 FLOAT,
                ma_qfq_5 FLOAT,
                ma_qfq_60 FLOAT,
                ma_qfq_90 FLOAT,
                macd_qfq FLOAT,
                macd_dea_qfq FLOAT,
                macd_dif_qfq FLOAT,
                mass_qfq FLOAT,
                ma_mass_qfq FLOAT,
                mfi_qfq FLOAT,
                mtm_qfq FLOAT,
                mtmma_qfq FLOAT,
                obv_qfq FLOAT,
                psy_qfq FLOAT,
                psyma_qfq FLOAT,
                roc_qfq FLOAT,
                maroc_qfq FLOAT,
                rsi_qfq_12 FLOAT,
                rsi_qfq_24 FLOAT,
                rsi_qfq_6 FLOAT,
                taq_down_qfq FLOAT,
                taq_mid_qfq FLOAT,
                taq_up_qfq FLOAT,
                trix_qfq FLOAT,
                trma_qfq FLOAT,
                vr_qfq FLOAT,
                wr_qfq FLOAT,
                wr1_qfq FLOAT,
                xsii_td1_qfq FLOAT,
                xsii_td2_qfq FLOAT,
                xsii_td3_qfq FLOAT,
                xsii_td4_qfq FLOAT,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (ts_code, trade_date)
            ) PARTITION BY RANGE (trade_date);
            """
            
            await self.db.execute(text(sql))
            await self.db.commit()
    
    async def _create_partition_table(self, table_name: str, year: int):
        """为指定年份创建分区表"""
        
        if table_name == "stock_factor_pro":
            partition_name = f"stock_factor_pro_{year}"
            start_date = f"{year}0101"
            end_date = f"{year + 1}0101"
            
            sql = f"""
            CREATE TABLE IF NOT EXISTS {partition_name} PARTITION OF stock_factor_pro
            FOR VALUES FROM ('{start_date}') TO ('{end_date}');
            """
            
            await self.db.execute(text(sql))
            await self.db.commit()
            
            index_sql = f"""
            CREATE INDEX IF NOT EXISTS idx_{partition_name}_ts_code ON {partition_name} (ts_code);
            CREATE INDEX IF NOT EXISTS idx_{partition_name}_trade_date ON {partition_name} (trade_date);
            """
            
            await self.db.execute(text(index_sql))
            await self.db.commit()